default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || '' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  timeout: 5000

development:
  database: <%= ENV['PG_DATABASE'] || 'queue_service_development' %>
  <<: *default

test:
  database: <%= ENV['PG_DATABASE'] || 'queue_service_test' %>
  <<: *default

production:
  database: <%= ENV['PG_DATABASE'] || 'queue_service_production' %>
  <<: *default
